### ISSUE TITLE
v4.1.0 still does not support deploying abiv2 contracts.

### ISSUE THREAD

**Issue by zhwir** [tronprotocol/tronweb#242]
When the function has a tuple type input parameter, deploying the contract throws an error:
TypeError: Cannot read property 'map' of null
    at ParamType.format (D:\worksync\wanchain-sc-sdk-tron\node_modules\@ethersproject\abi\lib\fragments.js:291:49)
    at D:\worksync\wanchain-sc-sdk-tron\node_modules\@ethersproject\abi\lib\fragments.js:696:85
    at Array.map (<anonymous>)
    at FunctionFragment.format (D:\worksync\wanchain-sc-sdk-tron\node_modules\@ethersproject\abi\lib\fragments.js:696:49)
    at D:\worksync\wanchain-sc-sdk-tron\node_modules\@ethersproject\abi\lib\interface.js:136:38
    at Array.forEach (<anonymous>)
    at new Interface (D:\worksync\wanchain-sc-sdk-tron\node_modules\@ethersproject\abi\lib\interface.js:110:24)
    at D:\worksync\wanchain-sc-sdk-tron\node_modules\tronweb\dist\TronWeb.node.js:1:104566
    at new e (D:\worksync\wanchain-sc-sdk-tron\node_modules\tronweb\dist\TronWeb.node.js:1:104750)
    at D:\worksync\wanchain-sc-sdk-tron\node_modules\tronweb\dist\TronWeb.node.js:1:116013

**Comment by llwslc** [comment]
We need more details. Did you pass these two parameters correctly?
```
createSmartContract({funcABIV2: [], parametersV2: []}, ...)
```

**Comment by zhwir** [comment]
I followed this guide: https://developers.tron.network/reference/tronwebcontractnew.
Both tronweb.contract.new and tronweb.contract.at throw the same error. In fact, the contract has been deployed to the chain, but the client code cannot parse abiv2 correctly, according to the call stack, the ‘components’ field of the tuple parameter is not loaded.

**Comment by llwslc** [comment]
Please pass the `funcABIV2` and `parametersV2` fields when deploying, and pass the correct abi when calling like this `tronweb.contrat(abi, address)`. We will update the abiv2 documentation as soon as possible.
