### ISSUE TITLE
invalid BigNumber value

### ISSUE THREAD

**Issue by Gr3it** [tronprotocol/tronweb#273]
I'm trying to instantiate a contract and I have to pass as an argument an amount with 18 decilams, I have tried to pass the value as bignumber but tronweb give an error, what I shoul use instead of BigNumber to pass as parameters to functions big numbers?

```const doubloonsPerBlock = tronWeb.toBigNumber("66000000000000000000");```
```
const masterChefContract = await tronWeb.contract().new({
    abi: MasterChefContract.abi,
    bytecode: MasterChefContract.bytecode,
    feeLimit: feeLimit,
    parameters: [
      tokensContract.address,
      devAddress,
      feeAddress,
      doubloonsPerBlock,
      startBlock,
    ],
  });
```
```
constructor(
        SpacePiratesTokens _doubloons,
        address _devaddr,
        address _feeAddress,
        uint256 _doubloonsPerBlock,
        uint256 _startBlock
    )
```
 ```
The error:
  Error: invalid BigNumber value (argument="value", value="66000000000000000000", code=INVALID_ARGUMENT, version=bignumber/5.6.2)
    at Logger.makeError (C:\Users\emanu\space-pirates-contracts\node_modules\@ethersproject\logger\src.ts\index.ts:261:28)
    at Logger.throwError (C:\Users\emanu\space-pirates-contracts\node_modules\@ethersproject\logger\src.ts\index.ts:273:20)
    at Logger.throwArgumentError (C:\Users\emanu\space-pirates-contracts\node_modules\@ethersproject\logger\src.ts\index.ts:277:21)
    at Function.BigNumber.from (C:\Users\emanu\space-pirates-contracts\node_modules\tronweb\node_modules\@ethersproject\bignumber\src.ts\bignumber.ts:289:23)
    at NumberCoder.encode (C:\Users\emanu\space-pirates-contracts\node_modules\tronweb\node_modules\@ethersproject\abi\src.ts\coders\number.ts:25:27)
    at C:\Users\emanu\space-pirates-contracts\node_modules\tronweb\node_modules\@ethersproject\abi\src.ts\coders\array.ts:71:19
    at Array.forEach (<anonymous>)
    at pack (C:\Users\emanu\space-pirates-contracts\node_modules\tronweb\node_modules\@ethersproject\abi\src.ts\coders\array.ts:54:12)
    at TupleCoder.encode (C:\Users\emanu\space-pirates-contracts\node_modules\tronweb\node_modules\@ethersproject\abi\src.ts\coders\tuple.ts:54:20)
    at AbiCoder.encode (C:\Users\emanu\space-pirates-contracts\node_modules\tronweb\node_modules\@ethersproject\abi\src.ts\abi-coder.ts:111:15) {
  reason: 'invalid BigNumber value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: BigNumber { s: 1, e: 19, c: [ 660000 ] }  
  ```
  Thank you a lot for your time

**Comment by llwslc** [comment]
Please use string directly.

```js
const masterChefContract = await tronWeb.contract().new({
    abi: MasterChefContract.abi,
    bytecode: MasterChefContract.bytecode,
    feeLimit: feeLimit,
    parameters: [
      tokensContract.address,
      devAddress,
      feeAddress,
      '66000000000000000000',
      startBlock,
    ],
  });
```
