### ISSUE TITLE
Struct as a function parameter causes an error when instantiating the contract.

### ISSUE THREAD

**Issue by carloshc** [tronprotocol/tronweb#289]
### First Problem

Network: Nile testnet.
Deploy: via TronIDE (ABI on chain), address `TVy8cpdRGvESJoacvGFf2NbVSwrig78PXt`
Scenario: a contract function has a struct as a parameter.

When the contract is instantiated in the backend (javascript, node) it gives the error.

Contract:
```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.6;

contract TestStruct {
    struct Numbers {
        uint256 param1;
        uint256 param2;
    }
 
    event Number(uint256 param1, uint256 param2);
 
    constructor() {}

    function logNumber(Numbers memory param) external {
        emit Number(param.param1, param.param2);
    }

}
```

Backend code:
```javascript
    let TestStruct = await tronWeb
      .contract()
      .at("TVy8cpdRGvESJoacvGFf2NbVSwrig78PXt");
```

Error:
```
TypeError: Cannot read properties of null (reading 'map')
    at ParamType.format (/Users/carloscampello/Code/Prexis/Labs/Researchers/Tron/TronWeb/node_modules/@ethersproject/abi/lib/fragments.js:291:49)
    at /Users/carloscampello/Code/Prexis/Labs/Researchers/Tron/TronWeb/node_modules/@ethersproject/abi/lib/fragments.js:696:85
    at Array.map (<anonymous>)
    at FunctionFragment.format (/Users/carloscampello/Code/Prexis/Labs/Researchers/Tron/TronWeb/node_modules/@ethersproject/abi/lib/fragments.js:696:49)
    at /Users/carloscampello/Code/Prexis/Labs/Researchers/Tron/TronWeb/node_modules/@ethersproject/abi/lib/interface.js:135:38
    at Array.forEach (<anonymous>)
    at new Interface (/Users/carloscampello/Code/Prexis/Labs/Researchers/Tron/TronWeb/node_modules/@ethersproject/abi/lib/interface.js:109:24)
    at /Users/carloscampello/Code/Prexis/Labs/Researchers/Tron/TronWeb/node_modules/tronweb/dist/TronWeb.node.js:1:114129
    at new e (/Users/carloscampello/Code/Prexis/Labs/Researchers/Tron/TronWeb/node_modules/tronweb/dist/TronWeb.node.js:1:114313)
    at /Users/carloscampello/Code/Prexis/Labs/Researchers/Tron/TronWeb/node_modules/tronweb/dist/TronWeb.node.js:1:125630
Finish script!
```

**Comment by llwslc** [comment]
For abi with structs, try this.

```js
    let TestStruct = await tronWeb
      .contract(abi, 'TVy8cpdRGvESJoacvGFf2NbVSwrig78PXt')
```
