### ISSUE TITLE
Multiple problems with Cloudflare workers

### ISSUE THREAD

**Issue by salirzv** [tronprotocol/tronweb#377]
I don't know if this project is meant to be used with workers or serverless in general, but I'm going to point to some of the problems I faced
at first there is this error 

`[ERROR] Could not resolve "querystring"

    node_modules/tronweb/dist/TronWeb.node.js:1:93004:
      1 │ ...on(t,e){t.exports=require("querystring")},function(t,e){t.export...`
and it was gone with `npm install querystring`

then is persisted that window object is undefined even tho I was using the node version directly from dist folder, and I tried to mock or fake the window object with every way that my knowledge would help me with, and the problem was still there

`Trace: ReferenceError: window is not defined
    at call (C:\Users\ali\AppData\Desktop\tg_hono\node_modules\tronweb\dist\webpack:\src\protocol\core\Tron_pb.js:16:43)
    at Object.call (C:\Users\ali\AppData\Desktop\tg_hono\node_modules\tronweb\dist\webpack:\src\protocol\core\Tron_pb.js:16:101)
    at require (C:\Users\ali\AppData\Desktop\tg_hono\node_modules\tronweb\dist\webpack:\webpack\bootstrap:19:22)
    at Module.call (C:\Users\ali\AppData\Desktop\tg_hono\node_modules\tronweb\dist\webpack:\src\utils\transaction.js:3:42)
    at __webpack_require__ (C:\Users\ali\AppData\Desktop\tg_hono\node_modules\tronweb\dist\webpack:\webpack\bootstrap:19:22)
    at module.exports (C:\Users\ali\AppData\Desktop\tg_hono\node_modules\tronweb\dist\webpack:\webpack\bootstrap:83:10)
    at node_modules/tronweb/dist/TronWeb.node.js (C:\Users\ali\AppData\Desktop\tg_hono\node_modules\tronweb\dist\webpack:\webpack\bootstrap:83:54)   
    at __require (C:\Users\ali\AppData\Local\Temp\tmp-17732-gj22esNm40GP\index.js:6:50)
    at C:\Users\ali\AppData\Desktop\tg_hono\src\index.ts:14:18
    at Hono.dispatch (C:\Users\ali\AppData\Desktop\tg_hono\node_modules\hono\dist\hono.js:139:15)
    at Hono.errorHandler (C:\Users\ali\AppData\Desktop\tg_hono\node_modules\hono\dist\hono.js:19:11)
    at Hono.handleError (C:\Users\ali\AppData\Desktop\tg_hono\node_modules\hono\dist\hono.js:125:19)
    at C:\Users\ali\AppData\Desktop\tg_hono\node_modules\hono\dist\hono.js:156:23
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

I think this package is not meant to work with serverless, and there is no related content anywhere to be found.
enlighten me if I'm wrong,
thanks for your time in advance

**Comment by summertanh** [comment]
You are right, we  do not meant to support any serverless env at present, but you can try to use the version under 5.0.0, such as [4.4.0](https://www.npmjs.com/package/tronweb/v/4.4.0). As the error info shows that the js pb can not  work with serverless, you can use the version without pb and test your feature. And we will plan to support the serverless env in the future. Thanks for your issue.

**Comment by wsdt** [comment]
does that mean that tronweb doesn't work at all on backend environments? @summertanh
