### ISSUE TITLE
TypeError: t.forEach is not a function

### ISSUE THREAD

**Issue by mehrdad517** [tronprotocol/tronweb#384]
I use Nodejs v18 and this is my code in a simple app.js file
```

const TronWeb = require('tronweb');


const tronWeb = new TronWeb(
    'https://api.shasta.trongrid.io',
    'https://api.shasta.trongrid.io',
    'https://api.shasta.trongrid.io'
  );
  const contractAbi = require('./contractAbi.json'); // Replace with the actual path to your ABI file
  const contractAddress = 'TWEv92whv1kDW3JqgNn5HHVhbfbnfhmQxC'; // Replace with the actual address of your smart contract

  const contract = tronWeb.contract(contractAbi, contractAddress);

console.log(contract);

```

TypeError: t.forEach is not a function
    at t.value (/root/test/node_modules/tronweb/dist/TronWeb.node.js:1:420180)
    at new t (/root/test/node_modules/tronweb/dist/TronWeb.node.js:1:418138)
    at s.value (/root/test/node_modules/tronweb/dist/TronWeb.node.js:1:457148)
    at Object.<anonymous> (/root/test/app.js:12:28)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

**Comment by start940315** [comment]
Make sure the abi is an array, not an object.

**Comment by mehrdad517** [comment]
@start940315 💯
