### ISSUE TITLE
Using tronweb in vite, the instance calls tronweb.address.fromHex('xxx'), which fails to convert to the trx chain address,

### ISSUE THREAD

**Issue by gxtgh** [tronprotocol/tronweb#488]
Using tronweb in vite, the instance calls tronweb.address.fromHex('xxx'), which fails to convert to the trx chain address, and an error message is reported: TypeError: (0, pt.createHash) is not a function. Warning in the browser: Module "crypto" has been externalized for browser compatibility. Cannot access "crypto.createHash" in client code. However, if the tronLink plug-in is used in the browser, the window.tronweb obtained can be converted normally.

**Comment by start940315** [comment]
You'll need to polyfill some packages that have not been packaged in vite:
```js
// vite.config.js

export default {
    resolve: {
        alias: {
            'crypto': 'crypto-browserify',
            'buffer': 'buffer/',
            'stream': 'readable-stream',
        }
    },
}
```
And you also need to add global variable in the very beginning of your code:
`window.global ||= window;`

**Comment by gxtgh** [comment]
你好，这个是可以了，但是有个问题，是这样的，运行时，页面提示Uncaught TypeError: Cannot read properties of undefined (reading 'slice')
    at node_modules/browserify-sign/node_modules/readable-stream/lib/_stream_writable.js (_stream_writable.js:57:81)
    at __require2 (chunk-W7S2ME4R.js?v=0f280abb:18:50)
    at node_modules/browserify-sign/node_modules/readable-stream/readable-browser.js (readable-browser.js:4:20)
    at __require2 (chunk-W7S2ME4R.js?v=0f280abb:18:50)
    at node_modules/browserify-sign/browser/index.js (index.js:5:14)
    at __require2 (chunk-W7S2ME4R.js?v=0f280abb:18:50)
    at node_modules/crypto-browserify/index.js (index.js:39:12)
    at __require2 (chunk-W7S2ME4R.js?v=0f280abb:18:50)
    at external node-commonjs "crypto":1:38
    at index.js:33:20

**Comment by theprashantparihar** [comment]
Hi, do I need to add window.global ||= window; in main.js? I have installed the three packages crypto-browserify, buffer and readable-stream. Added them in my vite.config.js as show above. But I am still getting the below error: 
ReferenceError: global is not defined
    at node_modules/randombytes/browser.js
